/**
 * Generated by MCP Agent - Playwright Test Generator
 * Target: Happy Testing Login Flow
 * Generated on: 2025-11-14
 * Tags: @auth @smoke @regression
 */

import { test, expect } from '@playwright/test';
import { LoginPage } from '../../pages/LoginPage';

test.describe('Login Flow Tests - MCP Generated', () => {
  let loginPage: LoginPage;

  test.beforeEach(async ({ page }) => {
    loginPage = new LoginPage(page);
    await loginPage.navigate();
  });

  test('should login successfully with valid credentials @smoke', async ({ page }) => {
    // Given: User is on login page
    await expect(loginPage.container).toBeVisible();
    
    // When: User enters valid credentials
    await loginPage.login('test@nutriapp.com', 'nutriapp123');
    
    // Then: User is redirected to dashboard
    await expect(page).toHaveURL(/\/dishes/);
    await expect(page.locator('[data-testid="dishes-container"]')).toBeVisible();
    await expect(page.locator('[data-testid="dishes-title"]')).toContainText('Sugerencias de Platillos');
  });

  test('should show error with invalid email format @negative', async ({ page }) => {
    // Given: User is on login page
    await expect(loginPage.container).toBeVisible();
    
    // When: User enters invalid email format
    await loginPage.emailInput.fill('invalid-email');
    await loginPage.passwordInput.fill('anypassword');
    await loginPage.submitButton.click();
    
    // Then: User remains on login page (browser validation prevents submit)
    await expect(page).toHaveURL(/\/login/);
    // And: Email input should show validation state
    await expect(loginPage.emailInput).toBeVisible();
  });

  test('should show error with wrong password @negative', async ({ page }) => {
    // Given: User is on login page
    await expect(loginPage.container).toBeVisible();
    
    // When: User enters valid email but wrong password
    await loginPage.login('test@nutriapp.com', 'wrongpassword');
    
    // Then: Login error should appear
    await expect(loginPage.errorMessage).toBeVisible();
    // And: User remains on login page
    await expect(page).toHaveURL(/\/login/);
  });

  test('should navigate to register page @navigation', async ({ page }) => {
    // Given: User is on login page
    await expect(loginPage.container).toBeVisible();
    
    // When: User clicks on register link
    await loginPage.goToRegister();
    
    // Then: User is redirected to register page
    await expect(page).toHaveURL(/\/register/);
    await expect(page.locator('[data-testid="register-container"]')).toBeVisible();
    await expect(page.locator('[data-testid="register-title"]')).toContainText('Crear cuenta');
  });

  test('should handle empty form submission @boundary', async ({ page }) => {
    // Given: User is on login page
    await expect(loginPage.container).toBeVisible();
    
    // When: User submits empty form
    await loginPage.submitButton.click();
    
    // Then: Required field validation should prevent submission
    await expect(loginPage.emailInput).toHaveAttribute('required');
    await expect(loginPage.passwordInput).toHaveAttribute('required');
    // And: User remains on login page
    await expect(page).toHaveURL(/\/login/);
  });
});

test.describe('Login Page UI Elements - MCP Generated', () => {
  test('should display all login form elements correctly @ui', async ({ page }) => {
    const loginPage = new LoginPage(page);
    await loginPage.navigate();

    // Verify all essential UI elements are present
    await expect(loginPage.container).toBeVisible();
    await expect(loginPage.title).toContainText('Bienvenido');
    await expect(loginPage.subtitle).toContainText('Inicia sesión para continuar');
    
    // Form elements
    await expect(loginPage.emailInput).toBeVisible();
    await expect(loginPage.passwordInput).toBeVisible();
    await expect(loginPage.submitButton).toBeVisible();
    await expect(loginPage.registerLink).toBeVisible();
    
    // Verify form elements are enabled
    await expect(loginPage.emailInput).toBeEnabled();
    await expect(loginPage.passwordInput).toBeEnabled();
    await expect(loginPage.submitButton).toBeEnabled();
  });
});